const SpotActionType = {
  FETCH_SUCCESS_CURRENCY_LIST: 'FETCH_SUCCESS_CURRENCY_LIST', // 获取所有币种-成功
  FETCH_ERROR_CURRENCY_LIST: 'FETCH_ERROR_CURRENCY_LIST', // 获取所有币种-失败
  UPDATE_WS_STATUS_V3: 'UPDATE_WS_STATUS_V3', // 更新ws连接状态 v3
  UPDATE_WS_ERR_COUNTER_V3: 'UPDATE_WS_ERR_COUNTER_V3', // 更新ws连接状态-失败计数器次数 v3
  UPDATE_WS_IS_DELAY: 'UPDATE_WS_IS_DELAY', // 更新ws登录是否延迟
  FETCH_SUCCESS_TICKERS: 'FETCH_SUCCESS_TICKERS', // 获取所有tickers-成功
  UPDATE_TICKERS: 'UPDATE_TICKERS', // 批量更新tickers
  FETCH_SUCCESS_INDEX_ALL: 'FETCH_SUCCESS_INDEX_ALL', // 获取所有index-成功
  UPDATE_ACTIVE_MARKET: 'UPDATE_ACTIVE_MARKET', // 更改交易区
  UPDATE_SEARCH: 'UPDATE_SEARCH', // 更改搜索条件
  UPDATE_SYMBOL: 'UPDATE_SYMBOL', // 更改当前币对
  COLLECT_PRODUCT: 'COLLECT_PRODUCT', // 收藏-取消收藏币对
  UPDATE_BILL_MENU: 'UPDATE_BILL_MENU', // 更新账单菜单的选中项

  UPDATE_THEME: 'UPDATE_THEME', // 更新主题
  UPDATE_CNY_RATE: 'UPDATE_CNY_RATE', // 人民币汇率

  UPDATE_HAS_OPEN_MARGIN: 'UPDATE_HAS_OPEN_MARGIN', // 币对中是否存在 杠杠
};
export default SpotActionType;
